version: "3"

includes:
  k8s-impl:
    taskfile: ./deploy/k8s/taskfile.yaml
    dir: ./deploy/k8s
  e2e:
    taskfile: ./test/e2e/taskfile.yaml
    dir: ./test/e2e

env:
  IMAGE_REPO: wsgw

vars:
  EXECUTABLE: wsgw
  APP: ./cmd/wsgw
  GOOS: linux
  GOARCH: amd64
  WSGW_LOG_FILE: '{{.WSGW_LOG_FILE | default "$HOME/workspace/logs/wsgw" }}'

tasks:
  clean:
    cmds:
      - go clean -testcache
  test-all:
    dotenv: [".test-env"]
    cmds:
      - go test -v -parallel 1 -timeout 600s ./test/...
  test-single:
    dotenv: [".test-env"]
    cmds:
      - go test -v -parallel 1 -timeout 10s ./test/... -run '^TestClusterSupportTestSuite$$' # -testify.m '^TestSendReceiveMessagesFromAppMultiClients$'
      # - go test -v -parallel 1 -timeout 60s ./test/... -run '^TestSendMessageTestSuite$$' -testify.m '^TestSendReceiveMessagesFromAppMultiClients$$'
  version_data:
    cmds:
      - echo "APPLICATION=WebSocket Gateway" > internal/config/version_data.txt
      - echo VERSION=0.0.1 >> internal/config/version_data.txt
      - printf "TIME=" >> internal/config/version_data.txt
      - date +%Y-%m-%dT%H:%M:%S%z >> internal/config/version_data.txt
      - printf "COMMIT=" >> internal/config/version_data.txt
      - git rev-parse HEAD >> internal/config/version_data.txt
  build:
    cmds:
      - task: version_data
      - |
        echo "GOOS {{.GOOS}} GOARCH {{.GOARCH}}"
        cd cmd
        env GOOS={{.GOOS}} GOARCH={{.GOARCH}} go build -o {{.EXECUTABLE}}
    sources:
      - ./cmd/**/*
      - ./internal/**/*
      - ./taskfile.yaml
    generates:
      - "{{.APP}}"
  watch:
    cmds:
      - |
        export WSGW_EXEC_NAME="{{.APP}}"
        export WSGW_LOG_FILE="{{.WSGW_LOG_FILE}}"
        export WSGW_SERVER_PORT=45679
        export WSGW_APP_BASE_URL=http://localhost:45678
        export WSGW_LOAD_BALANCER_ADDRESS=localhost:5173
        export LOG_LEVEL=debug
        ./watch.sh
  image:
    cmds:
      - task: build
      - cp {{.APP}} deploy/docker/
      - |
        if which minikube && minikube status;
        then
          eval $(minikube -p minikube docker-env)
        fi
        docker build -t wsgw:latest deploy/docker/
  k8s:
    cmds:
      - task: image
      - task: k8s-impl:single
  image-k8s-all:
    cmds:
      - task: image
      - task: k8s
      - task: e2e:app:image
      - task: e2e:k8s-impl:app
      - task: e2e:client:image
      - task: e2e:k8s-impl:client
  k8s-clustered:
    cmds:
      - task: image
      - task: k8s:clustered
  cluster:
    cmds:
      - task: image
      - kubectl apply -f deploy/k8s/redis-config.yaml
      - kubectl apply -f deploy/k8s/redis-deployment.yaml
      - kubectl apply -f deploy/k8s/redis-service.yaml
