version: "3"

env:
  IMAGE_REPO: wsgw

vars:
  NAMESPACE: '{{.NAMESPACE | default "default" }}'

tasks:
  single:
    cmds:
      - kubectl -n {{.NAMESPACE}} apply -f wsgw-deployment.yaml
      - kubectl -n {{.NAMESPACE}} apply -f wsgw-service.yaml
      - kubectl -n {{.NAMESPACE}} rollout restart deployment wsgw
  clustered:
    cmds:
      - task: single
      - kubectl -n {{.NAMESPACE}} apply -f redis-config.yaml
      - kubectl -n {{.NAMESPACE}} apply -f redis-deployment.yaml
      - kubectl -n {{.NAMESPACE}} apply -f redis-service.yaml
