apiVersion: apps/v1
kind: Deployment
metadata:
  name: wsproxy
  labels:
    app: wsproxy
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wsproxy
  template:
    metadata:
      labels:
        app: wsproxy
    spec:
      containers:
      - name: wsproxy
        image: wsproxy
        imagePullPolicy: Never
        env:
        - name: MY_INSTANCE_IPADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_INSTANCE_PORT
          value: "8080"
        - name: MY_INSTANCE_PROTOCOL
          value: "http"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
